
name: Lint

on:
  pull_request:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # BEGIN Dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      # END Dependencies

      - name: Print
        run: |
          ruby lint.rb bad.md
      - name: Format Locally
        run: |
          ruby lint.rb bad.md | reviewdog -filter-mode=nofilter -f=rdjsonl
      - name: Post to Github
        run: |
          ruby lint.rb bad.md | reviewdog -filter-mode=nofilter -reporter=github-pr-review -f=rdjsonl
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
