
name: Lint

on:
  pull_request:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # BEGIN Dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      # END Dependencies
      - name: Deps
        run: |
          pip install pyyaml

      - name: Print
        run: |
          python lint.py --path tools/jbrowse/
      - name: Format Locally
        run: |
          python lint.py --path tools/jbrowse/ | reviewdog -filter-mode=nofilter -f=rdjsonl
      - name: Post to Github
        run: |
          python lint.py --path tools/jbrowse/ | reviewdog -filter-mode=nofilter -reporter=github-pr-review -f=rdjsonl
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
