
name: Lint

on:
  push:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # BEGIN Dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      # END Dependencies

      - name: Check Citations
        run: |
          ruby lint.rb bad.md | reviewdog -filter-mode=file -reporter=github-pr-check -f=rdjsonl
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
