name: "[Social] Autogenerate missing social media cards"

on:
  push:

jobs:
  runner-job:
    if: github.repository_owner == 'hexylena'
    runs-on: ubuntu-24.04
    steps:
      # Shallow should be fine for video
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # BEGIN Dependencies
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get install -y imagemagick optipng inkscape
          pip install requests awscli
          mkdir -p ~/.fonts/
          wget https://galaxy-training.s3.amazonaws.com/social/recursive.ttf -O ~/.fonts/recursive.ttf
          fc-cache -rv
      # END Dependencies

      - name: Build Social Media Cards
        run: |
          convert -density 100 event.svg event.png
          optipng event.png
          convert -density 100 tutorial.svg tutorial.png
          optipng tutorial.png

      - name: Output image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: '*.png'
